version: '3'
services:
  redis:
    image: redis:3.2-alpine3.8
    ports:
      - "6379:6379"
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379/1
      CLIENTS: 0
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - redis
      - client
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app
