FROM python:2.7.15-alpine

RUN apk update
RUN mkdir /app
WORKDIR /app

COPY ./requirements.txt .

RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED 1

RUN chmod 775 -R /app

RUN ls -alrt /app

EXPOSE 5000

ENTRYPOINT ["python", "/app/src/client.py"]

